- name: Installing Nginx
  ansible.builtin.package:
    name: nginx 
    state: present 

- name: Starting Nginx Service 
  ansible.builtin.service:
    name: nginx 
    state: started
    enabled: yes

#- name: Download and extract {{COMPONENT}}
#  ansible.builtin.unarchive:
#    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp 
#    remote_src: yes 

- name:  Download and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download-and-extract  

#- name: Cleanup of old html content 
 # ansible.builtin.file:
  #  path: /usr/share/nginx/html/
   # state: absent

#- name: Coping frotend context to nginx path 
 # ansible.builtin.copy:
  #  src: /tmp/frontend-main/static/
   # dest: /usr/share/nginx/html/
   # remote_src: yes

#- name: Coping proxy config 
#  ansible.builtin.copy:
#    src: roboshop.conf 
#    dest: /etc/nginx/default.d/roboshop.conf

- name: Coping proxy config 
  ansible.builtin.template:
    src: roboshop.conf 
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restarting Nginx Service  
  
#- name: Coping proxy config 
 # ansible.builtin.copy:
  #  src: roboshop.conf 
   # dest: /etc/nginx/default.d/roboshop.conf

#- name: Starting Nginx Service 
#  ansible.builtin.service:
#    name: nginx 
#    state: restarted
#    enabled: yes


#- name: Configuing system name 
 # ansible.builtin.include_role:
  #  name: common 
   # tasks_from: set-hostname